import json

from agent.llm import get_llm
from agent.states import AgentState
from agent.prompts import (
    PLANNER_PROMPT,
    ARCHITECT_PROMPT,
    CODER_PROMPT,
    REVIEWER_PROMPT,
    DEBUGGER_PROMPT,
)
from agent.tools import (
    create_project,
    create_file,
    write_file,
)
llm = get_llm()
def planner_node(state: AgentState) -> AgentState:
    """
    Planner Agent
    Reads the user's request and creates a project plan.
    """

    print("\n========== Planner Started ==========")

    prompt = PLANNER_PROMPT.format(
        user_request=state["user_request"]
    )

    response = llm.invoke(prompt)

    # Save planner output
    state["project_plan"] = response.content

    # Update state
    state["status"] = "planning_completed"
    state["logs"].append("Planner completed successfully")

    return state

def architect_node(state: AgentState) -> AgentState:
    """
    Architect Agent
    Converts the project plan into coding tasks.
    """

    print("\n========== Architect Started ==========")

    prompt = ARCHITECT_PROMPT.format(
        project_plan=state["project_plan"]
    )

    response = llm.invoke(prompt)

    try:
        tasks = json.loads(response.content)

    except Exception as e:

        print("Failed to parse JSON:", e)

        tasks = []

    state["tasks"] = tasks

    state["status"] = "architecture_completed"

    state["logs"].append("Architect completed successfully")

    return state

def coder_node(state: AgentState) -> AgentState:
    """
    Coder Agent
    Generates code for each task and saves it as a file.
    """

    print("\n========== Coder Started ==========")

    # Temporary project name
    project_name = state["user_request"].replace(" ", "_")

    # Create project folder
    create_project.invoke(
        {
            "project_name": project_name
        }
    )

    # Generate every file
    for task in state["tasks"]:

        state["current_task"] = task

        prompt = CODER_PROMPT.format(
            file_name=task["file_name"],
            instructions=task["instructions"]
        )

        response = llm.invoke(prompt)

        state["current_code"] = response.content

        create_file.invoke(
            {
                "project_name": project_name,
                "file_name": task["file_name"],
                "content": response.content
            }
        )

        state["generated_files"].append(
            task["file_name"]
        )

        print(f"Created: {task['file_name']}")

    state["status"] = "coding_completed"

    state["logs"].append(
        "Coder completed successfully"
    )

    return state

def reviewer_node(state: AgentState) -> AgentState:
    """
    Reviewer Agent
    Reviews the code generated by the Coder.
    """

    print("\n========== Reviewer Started ==========")

    prompt = REVIEWER_PROMPT.format(
        code=state["current_code"]
    )

    response = llm.invoke(prompt)

    state["review"] = response.content

    state["status"] = "review_completed"

    state["logs"].append(
        "Reviewer completed successfully"
    )

    return state

def debugger_node(state: AgentState) -> AgentState:
    """
    Debugger Agent
    """

    print("\n========== Debugger Started ==========")

    prompt = DEBUGGER_PROMPT.format(
        review=state["review"],
        code=state["current_code"]
    )

    response = llm.invoke(prompt)

    state["current_code"] = response.content

    write_file.invoke(
        {
            "project_name": state["user_request"].replace(" ", "_"),
            "file_name": state["current_task"]["file_name"],
            "content": response.content
        }
    )

    state["retry_count"] += 1

    state["status"] = "debug_completed"

    state["logs"].append(
        "Debugger fixed the file."
    )

    return state