from pydantic import BaseModel
from typing import List


class Task(BaseModel):
    """
    Represents one coding task generated by the Architect.
    """

    file_name: str

    instructions: str


class Review(BaseModel):
    """
    Review generated by the Reviewer Agent.
    """

    status: str

    comments: List[str]